In [58]:
import numpy as np;
from numpy.linalg import eig
import networkx as nx

Function To Find Pagerank Centrality

In [59]:
def find_pagerank_centrality(graph):
    G = nx.from_numpy_array(graph)
    pr = nx.pagerank(G, weight=None, alpha=0.85, max_iter=100000)
    
    return pr

Function To Find Katz Centrality

In [60]:
def find_katz_centrality(graph, eigen_value):
    max_eigen_value = max(eigen_value)
    G = nx.from_numpy_array(graph)    
    katz_centrality = nx.katz_centrality(G, weight= None, alpha = 1/(max_eigen_value+1), max_iter = 100000)
    
    return katz_centrality

Function To Find EigenValue & EigenVectors

In [61]:
def find_eigens(graph):
    eigen_value, eigen_vector = eig(graph)
    
    return eigen_value, eigen_vector

Function To Find Degree Of An Undirected Unweighted Graph

In [63]:
def get_degree_graph(graph):
    degree_graph = np.zeros((5,5))

    index = 0;
    for row in graph:
        degree = 0
        for element in row:
            if element != 0:
                degree += 1
        
        degree_graph[index][index] = degree
        index += 1

    return degree_graph 
        

In [69]:
# Defining the 3 different graphs.

# Complete graph
complete_graph = np.array([
    [0, 1, 1, 1, 1],
    [1, 0, 1, 1, 1],
    [1, 1, 0, 1, 1],
    [1, 1, 1, 0, 1],
    [1, 1, 1, 1, 0]
])

# Cycle graph
cycle_graph = np.array([
    [0, 1, 0, 0, 1],
    [1, 0, 1, 0, 0],
    [0, 1, 0, 1, 0],
    [0, 0, 1, 0, 1],
    [1, 0, 0, 1, 0]
])


# Star topology
star_graph = np.array([
    [0, 1, 1, 1, 1],
    [1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0]
])

index = 0
graphs = [complete_graph, cycle_graph, star_graph]

for graph in graphs:
    print("------------------------------------------ Complete Graph ------------------------------------------") if index == 0 else print("------------------------------------------ Cycle Graph ------------------------------------------") if index == 1 else print("------------------------------------------ Star Graph ------------------------------------------")
    print("Degree Graph: \n", get_degree_graph(graph))
    eigen_value, eigen_vector = find_eigens(graph)
    print("Eigen Vector: \n", eigen_vector)
    print("Katz Centrality: ", find_katz_centrality(graph, eigen_value))
    print("Page Rank Centrality: ", find_pagerank_centrality(graph))
    print()
    index += 1


------------------------------------------ Complete Graph ------------------------------------------
Degree Graph: 
 [[4. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 4.]]
Eigen Vector: 
 [[-0.89442719  0.4472136   0.19518001  0.15432036  0.09319422]
 [ 0.2236068   0.4472136  -0.53674504  0.73302172 -0.25628411]
 [ 0.2236068   0.4472136   0.76445506  0.04715344 -0.25628411]
 [ 0.2236068   0.4472136  -0.21144502 -0.46724776 -0.41160781]
 [ 0.2236068   0.4472136  -0.21144502 -0.46724776  0.8309818 ]]
Katz Centrality:  {0: 0.4472135954999579, 1: 0.4472135954999579, 2: 0.4472135954999579, 3: 0.4472135954999579, 4: 0.4472135954999579}
Page Rank Centrality:  {0: 0.2, 1: 0.2, 2: 0.2, 3: 0.2, 4: 0.2}

------------------------------------------ Cycle Graph ------------------------------------------
Degree Graph: 
 [[2. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 2.]]
Eigen Vector: 
 [[ 0.63245553 -0.63245553 -0.4472136  -0