In [1]:
import numpy as np;

In [2]:
def findLinearAverage(state, graph):
    num_nodes = len(state)
    new_state = np.zeros(num_nodes)
    for i in range(num_nodes):
        neighbors = np.where(graph[i] == 1)[0]
        num_neighbors = len(neighbors)
        if num_neighbors > 0:
            new_state[i] = np.sum(state[neighbors]) / num_neighbors
        else:
            new_state[i] = state[i]
    return new_state

In [8]:
def checkConvergenceAndLinearAverages(state, graph):
    iteration = 0;
    while True:
        next_state = findLinearAverage(state, graph)
        if(np.allclose(state,next_state, atol=1e-5)):
            break

        state = next_state
        iteration += 1
    
    print(iteration + 1)
    print(state)

In [9]:
# Define initial_states
initial_states = np.array([1., -1., 1., -1., 1.])

# Defining the 3 different systems.
# Complete graph
complete_graph = np.ones((5,5))

# Cycle graph
cycle_graph = np.array([
        [1, 1, 0, 0, 1],
        [1, 1, 1, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1]
    ])


# Star topology. center = node 1
star_graph = np.array([
        [1, 1, 1, 1, 1],
        [1, 1, 0, 0, 0],
        [1, 0, 1, 0, 0],
        [1, 0, 0, 1, 0],
        [1, 0, 0, 0, 1]
    ])

graphs = [complete_graph, cycle_graph, star_graph]

for graph in graphs:
    checkConvergenceAndLinearAverages(initial_states, graph)

2
[0.2 0.2 0.2 0.2 0.2]
17
[0.20002051 0.19999217 0.19997465 0.19999217 0.20002051]
17
[0.38461539 0.38460012 0.38463064 0.38460012 0.38463064]
